---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneendpoints
  - keystoneservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbaccounts
  - mariadbdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbaccounts/finalizers
  - mariadbdatabases/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - octavia.openstack.org
  resources:
  - octaviaamphoracontrollers
  - octaviaapis
  - octaviarsyslogs
  - octavias
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - octavia.openstack.org
  resources:
  - octaviaamphoracontrollers/finalizers
  - octaviaapis/finalizers
  - octavias/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - octavia.openstack.org
  resources:
  - octaviaamphoracontrollers/status
  - octaviaapis/status
  - octaviarsyslogs/status
  - octavias/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - octavia.openstack.org
  resources:
  - octaviarsyslogs/finalizers
  verbs:
  - update
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovndbclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.openstack.org
  resources:
  - redises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  - hostmount-anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - topology.openstack.org
  resources:
  - topologies
  verbs:
  - get
  - list
  - update
  - watch
